# app:
#     resource: "@AppBundle/Controller/"
#     type:     annotation
sub_home:
  path: /{count}
  host: "{subdomain}.%base_domain%"
  defaults: { _controller: AppBundle:Lucky:number }

main_home:
  path: /
  defaults: { _controller: AppBundle:Default:index }
